SL-18330: Use new standalone llsd module instead of llbase.llsd.
secondlife/leap pull request #14
Opened 2023-03-13 19:07 UTC by nat-goodspeed

Ongoing development has moved to [standalone llsd](https://github.com/secondlife/python-llsd) instead of llbase.llsd. In particular, [the new llsd.parse()](https://github.com/secondlife/python-llsd/pull/4) has greatly improved ability to correctly parse the stdin stream from the viewer.

2023-03-13 19:32 UTC, nat-goodspeed commented
n.b. 

    RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'

Not an actual problem with this PR.

2023-03-14 14:29 UTC, nat-goodspeed commented
Merged [the llsd PR](https://github.com/secondlife/python-llsd/pull/4), essential for this fix, but the pre-commit check is still busted due to invalid Poetry configuration -- not the code.

2023-03-14 16:58 UTC, simon-linden approved these changes
Some of the most important one line commits I've seen in a while - nice to have that self-contained!

2023-03-14 19:35 UTC, bennettgoble commented
@nat-goodspeed I suspect the pre-commit action is failing due to a cached dependency conflicting with a newer version of python that is getting pulled in by pre-commit.yaml's setup-python step. You could pin the python version used to[ the last CI run of pre-commit that passed](https://github.com/secondlife/leap/actions/runs/4189116695/jobs/7261058962), 3.11.1 to possibly solve the CI issue without disabling linting/tests.

2023-03-14 19:36 UTC, bennettgoble commented on .pre-commit-config.yaml
> -      args: [--line-length=120]
Even if the CI/CD configuration is being removed I don't see why the pre-commit configuration itself needs to be removed.

2023-03-14 19:36 UTC, bennettgoble commented on .github/workflows/pre-commit.yaml
> -          python-version: 3.x
Suggestion: pin to 3.11.1

2023-03-14 20:40 UTC, bennettgoble commented
My previous suggestion is not correct, it looks like one of the linters specified in the pre-commit-config had an incompatibility with the latest version of poetry. Fixed in #15. Once this is merged, rebase and things should be good.

2023-03-14 20:41 UTC, bennettgoble requested changes
Requires #15

2023-03-15 15:00 UTC, nat-goodspeed commented
Closing: I'll resubmit without the flailing commits attempting to disable the pre-commit check.

2023-03-15 15:00 UTC, closed without merging